### ISSUE TITLE
NTR: Micro-litter Size Classes and Types

### ISSUE THREAD

**Issue by timvdstap** [nvs-vocabs/EMODnetChemVocabs#13]
Hi, 

I'm currently working on standardizing a microplastic/micro-litter dataset, and unfortunately the terms used for microlitter-type and -size are different from the ones that have been used to develop vocabulary for EMODnet. I was therefore wondering to what extent it would be possible to expand on the terms in the H01 and H03 repositories. If this is not the right place to ask, I apologize. The article that I'm standardizing can be found here: https://doi.org/10.1088/1748-9326/abbb4f - and more specifically, I am hoping to create standardized vocabulary for the size classes and plastic types listed below. Whilst the current available controlled vocabulary often partially describes the terms, I feel like the proposed size classes and types are more encompassing.  

Size Classes - H03:
**0.5 to 1.5 millimetres** - Small microplastics. Micro-litter particles that pass through a 1.5 millimetre mesh screen but are retained by a 0.5 millimetre mesh.
**1.5 to 5 millimetres** - Large microplastics. Micro-litter particles that pass through a 5 millimetre mesh screen but are retained by a 1.5 millimetre mesh.
**5 to 15 millimetres** - Small mesoplastics. Micro-litter particles that pass through a 15 millimetre mesh screen but are retained by a 5 millimetre mesh.
**15 to 50 millimetres** - Large mesoplastics. Micro-litter particles that pass through a 50 millimetre mesh screen but are retained by a 15 millimetre mesh.

Microlitter Type - H01:
**H-type** - Fragments and objects made of hard plastic, plastic sheet or film. 
**N-type** - Fragments of plastic lines, ropes, and fishing nets
**P-type** - Pre-production plastic pellets in the shape of a cylinder, disk or sphere
**F-type** - Fragments or objects made of foamed material (e.g. expanded polystyrene)

The plastic size classes and type categories used are after _Lebreton et al. 2018_ (https://www.nature.com/articles/s41598-018-22939-w#citeas). While I was not involved with data collection or processing, should you have any questions I'd be more than happy to forward these to the authors / my data provider. 

Thank you in advance,

Tim

**Comment by gwemon** [comment]
@timvdstap thank you for posting this message. I will make the EMODnet chemistry micro-litter group aware of your request.

**Comment by timvdstap** [comment]
@gwemon Thank you Gwen! If there are any concerns or questions, please let me know.

**Comment by mmolinajack** [comment]
Dear @timvdstap,
thanks for your proposal. 
We established the vocabularies according to different examples from different institutions and considering the Guidance on Monitoring of Marine Litter in European Seas (MSFD Technical Subgroup on Marine Litter, 2013).
However they can be updated if needed. Regarding the size classes, we will proceed to enlarge the vocabulary with these new terms as we consider that it might facilitate the inclusion of new data in the Platform.
With regard to the litter types, we think that this might need a deeper analysis and discussion. We will consider your proposal but take into account that the types that you are proposing mix somehow types, with shapes and also with materials. Shapes, materials and types are different vocabularies that during data reporting can be specified. 
Best,
Eugenia

**Comment by timvdstap** [comment]
Hi @mmolinajack ,

Thank you for getting back to me, and for including these size classes. With regards to the litter types, I understand that perhaps creating new vocabulary for these types is excessive given that vocabulary of types, shapes and materials exists. I appreciate you looking into it though, and I will get in touch with the data providers to see if they know whether their way of formulating or classifying microplastics has found some traction in the scientific community. 

Is there anything else you need from me with regards to the creation of the size classes?

Thank you!

**Comment by mmolinajack** [comment]
Hi @timvdstap,
We will discuss about the size classes with @gwemon and get back to you if we need any more details, thanks!
Regarding types, please, let us know feedback from data providers as it will be very useful as part of a deeper discussion.
Cheers,
Eugenia

**Comment by timvdstap** [comment]
Hi @mmolinajack ,

I've received an email from the data provider regarding their use, and likely future use, of plastic types. As it's a rather elaborate email, I'd like to forward this to you - where can I best reach you at? Thanks in advance!
Cheers, Tim

**Comment by mmolinajack** [comment]
Hi @timvdstap,
you can send it to mmolinajack@inogs.it. Please, put in copy nodc@inogs.it so that my colleagues can also read it as it might be interesting for some of us.
Thanks!!
Cheers,
Eugenia

**Comment by gwemon** [comment]
@timvdstap and @mmolinajack I will add these categories to H03 in the next couple of days. Tim, all your definitions include e.g. Manta net mesh size. H03 already had 2 size ranges associated with Manta net mesh size: 1-2mm and 1-5mm. I would like to better understand why it is important to single out Manta net as an example for these size-categories? Also the size of a net's  mesh will define the lower size range pretty well but the higher size range will need to be determined at post-sampling stage. Am I right? Just wondering if we should not tweak these defintions a little. Here is the definition we have in L22 for a [generic Manta net](http://vocab.nerc.ac.uk/collection/L22/current/NETT0177/) and the [original Manta net](http://vocab.nerc.ac.uk/collection/L22/current/NETT0088/).

**Comment by timvdstap** [comment]
Hi @gwemon,

Thank you for including those size ranges. I don't think there's a need to single out Manta net any longer, as sampling instrument name and associated definitions will be recorded separatedly from sampling instrument parameters. For the definitions I was following along with some definitions already recorded in the H03 repo. 

You are right that the higher size range will be determined post-sampling stage. I see now that some of my definitions do indeed need to be tweaked - thank you for pointing this out! 

Do you still think it's good to include e.g. "pass through a 5 millimetre mesh screen but are retained by a 1.5 millimetre mesh" in the definition? Following the sampling methods in the Lebreton _et al. 2018_ paper, particles were picked with tweezer and measured with a ruler, and not separated through a sieve.

(From the paper): _Subsequently, floating objects and particles attached to biomass identified as buoyant anthropogenic debris according to the criteria described in (Hidalgo-Ruz et al 2012) were hand-picked using stainless-steel tweezers and their widest dimension was measured with a ruler. The picked particles were separated into the four size classes introduced in (Lebreton et al 2018)_

**Comment by gwemon** [comment]
@timvdstap Yes, I agree that the definitions will need to be made broader in order to reflect the various techniques used to determined microlitter particle sizes. @mmolinajack is that okay with you?

**Comment by mmolinajack** [comment]
Yes, I agree with the proposal.
Thanks @gwemon.

**Comment by gwemon** [comment]
Sorry I am picking this up again after a long delay. I am proposing to simplify the definitions to the extreme and simply say:

"A size-class used for micro-litter particle monitoring."

i.e. the same definition for every size class since we cannot be specific about the sampling or measuring protocols and assume that sieves or measuring devices have been used and since all that matters for this vocabualry is to state clearly what the terms and codes are used for.

@mmolinajack are you happy with this?

**Comment by mmolinajack** [comment]
Yes, @gwemon we agree with the proposal, thanks!
P.S. Could you please add Matteo (mattevi78) to the Github? Thanks!

**Comment by gwemon** [comment]
The request to extend the H03 vocabulary with additional size-classes has now been carried through and the changes were made to the NVS H03 collection.

@mmolinajack  @mattevi78 For the extension of H01 with categories described in Lebreton et al 2018 (see detail above), I suggest that this be transferred to a ticket under the H01 repository: https://github.com/nvs-vocabs/H01/issues once a decision has been made.

**Comment by mmolinajack** [comment]
Thanks @gwemon, it is a good idea

**Comment by timvdstap** [comment]
Hi @gwemon, thank you for picking this up again! Do you think it would be possible to extend the definition to:

_"A size-class used for micro-litter particle measurement or monitoring._ To me, monitoring implies systematic observation over a period of time, whereas this is not always the case. 

edit: Although I see now that the definitions have also been included to the H03 repository -- thank you!

**Comment by gwemon** [comment]
@timvdstap I missed or read but then forgot to react to your last comment. I see your point and keep this ticket until I have time to review this. Thank you.

**Comment by gwemon** [comment]
@mmolinajack I am reviewing outstanding tickets and see that this one is still opened. Could you say whether you approve the change suggested by @timvdstap to the definitions of the H03 terms (https://vocab.nerc.ac.uk/collection/H03/current/)
to be changed from "A size-class used for micro-litter particle monitoring." to "A size-class used for micro-litter particle measurement or monitoring."? Also I noticed that some terms say "microns" and some say "micrometres" so I am proposing to harmonise this by using "micrometres". Do you agree?

**Comment by mmolinajack** [comment]
Yes, both suggestions seem reasonable.
Thanks,
Eugenia

**Comment by gwemon** [comment]
Changes implemented and queued for publication on the NVS.

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/H03/current/
