### ISSUE TITLE
Additional P01 to report micro-litter on the single particle level

### ISSUE THREAD

**Issue by mmolinajack** [nvs-vocabs/EMODnetChemVocabs#18]
At present, the identification of marine microlitter include optical and spectroscopic methodologies but  the monitoring is evolving through the use of new analytical techniques such as FTIR, RAMAN, NIR, pyrolysis MS.  This change will result in the need for a change in the reporting, providing microlitter data describing each single particle. The reporting of marine microlitter particles on the single item level requires the creation of 3 new P01s to describe: Particle ID, particle length and particle width.

**Comment by gwemon** [comment]
This publication: https://journals.sagepub.com/doi/full/10.1177/0003702820929064 seems to relevant

**Comment by mmolinajack** [comment]
Thanks @gwemon very interesting

**Comment by gwemon** [comment]
Codes created

**Comment by mmolinajack** [comment]
Thanks!
