### ISSUE TITLE
Review of H01 vocabulary to describe the morphology of the particles. Change the name of the vocabulary to EMODnet micro-litter morphology (BODCNVS-1424)

### ISSUE THREAD

**Issue by mmolinajack** [nvs-vocabs/EMODnetChemVocabs#19]
The H01 vocabulary includes information mainly related to the morphology of the particles. However, in some terms there is an inclusion of information related to the material: “microplastic”, “non-plastic” or “man-made”. It would be better to refine the vocabulary, including references only related to the description of the morphology and change the name of the vocabulary to EMODnet micro-litter morphology.

**Comment by mmolinajack** [comment]
Hi @gwemon,
The text of the new microlitter guidance of JRC is ongoing. They are using EMODnet microlitter vocabularies for the reporting. In our opinion it will be the moment to update the H01 in order to split the information regarding morphology and material.
We propose  to have the following terms in the H01 vocabulary:

- Filaments
- Pellets
- Films
- Fragments
- Foams
- Items
- Granules (once the definition is final)

This means that:
-One of the terms regarding filaments, ([[H0100004](http://vocab.nerc.ac.uk/collection/H01/current/H0100004)] or ([[H0100008](http://vocab.nerc.ac.uk/collection/H01/current/H0100008)], must be deprecated.
-All labels and definitions have to be reviewed in order to eliminate the references to the materials.
-The term [[H0100007](http://vocab.nerc.ac.uk/collection/H01/current/H0100004)] "non-plastic man-made micro-particles (e.g. glass, metal, tar)" has to be deprecated.

At the same time, we have to include the information regarding the materials in the H05 vocabulary. At present, the information regarding the material in H01 is the following:
-Non plastic:

1. rubber
2. natural fibers

-Non plastic man-made:

1. glass
2. metal
3. tar

We need to decide how to include this information in the vocabulary. We propose to create generic and specific terms, to cover all the possibilities: rubber, natural fibers, glass, metal, tar, plastic, non-plastic, non-plastic man-made

What do you think? 
Thanks,
Eugenia and Matteo

**Comment by gwemon** [comment]
@mmolinajack @[mattevi78](https://github.com/mattevi78) 
I have implemented the requested changes to H01 to all concepts but the H010001 (i.e. "microplastic items"). See below:
H0100001	microplastic items	A generic term for any kind of micro-litter item made of any kind of plastic material.
H0100002	fragments	Irregularly-shaped plastic micro-litter particles with broken off edges that may be rounded or angular.
H0100003	pellets	Micro-litter particles from industrial origin only. In comparison with granules, pellets are usually flat on one side, rough surface and irregular, round shapes. Normally bigger in size.
H0100004	filaments	Slender thread-like micro-litter particles.
H0100005	films	Micro-litter particles derived from plastic sheets or thin plastic films.
H0100006	foams	Any kind of micro-litter particle made of plastic foam, including styrofoam.
H0100007	non-plastic man-made micro-particles (e.g. glass, metal, tar)	Term deprecated on 2022/06/28 following review of the H01 categories; see https://github.com/nvs-vocabs/EMODnetChemVocabs/issues/19. A generic term for any kind of micro-litter item that is not made of plastic.
H0100008	non-plastic filaments (natural fibres, rubber)	Term deprecated on 2022/06/28 following review of the H01 categories; see https://github.com/nvs-vocabs/EMODnetChemVocabs/issues/19. Filaments of non-plastic material such as natural fibres or rubber that are present in micro-litter samples.
H0100009	granules	Micro-litter particles with smooth spherical shape. In comparison with pellets, they have a rounder shape and are smaller in size.

Changes will be live on the NVS tomorrow.

For H010001, could you advise? I am not keen to create a term labelled "Items" in a vocabulary that is about shapes. What is the purpose of this term? If it is for undefined or "other" shapes then it would be better to have a term with preferred label "not specified" to be used when the shape is not specified and, if you think that an "other shapes" term is needed, then we could add a new term for this too. In this case, I would probably recommend to deprecate H010001 and create the 2 new terms "not specified" and "other shapes".

**Comment by gwemon** [comment]
@mmolinajack  @mattevi78 Regarding required changes to H05 to cater for non-plastic material, you suggested: "We propose to create generic and specific terms, to cover all the possibilities: rubber, natural fibers, glass, metal, tar, plastic, non-plastic, non-plastic man-made"
We already have synthetic rubber in H05 so just having a term "rubber" would be confusing. How about "natural rubber"?
then "natural fibres", "glass", "metal". I think the term "tar" maybe be too broad. Do we mean "petroleum tar"? Do we have other terminologies from other protocols to use as a reference? Also, the inclusion of the last 2 suggested categories might be quite confusing. Maybe labels such as "undefined plastic" and "undefined non-plastic" would be more useful.

**Comment by mmolinajack** [comment]
Hi @gwemon,
the first session of the TGML meeting took place today and will be following tomorrow and on Thursday. Some of the elements that we discussed above and on the other issues, seem to be under discussion again within the group of experts. We would prefer if we wait to see how the discussions proceed during the following days. We will be back to you on Friday after the meeting is finished. Hope you understand and sorry for this change on the last moment.

**Comment by gwemon** [comment]
@mmolinajack that's okay. some of the changes requested are already live as you know but I put all the other chenges requested on hold for now. Please let us know how to proceed when ready.

**Comment by mmolinajack** [comment]
> @mmolinajack @mattevi78 Regarding required changes to H05 to cater for non-plastic material, you suggested: "We propose to create generic and specific terms, to cover all the possibilities: rubber, natural fibers, glass, metal, tar, plastic, non-plastic, non-plastic man-made" We already have synthetic rubber in H05 so just having a term "rubber" would be confusing. How about "natural rubber"? then "natural fibres", "glass", "metal". I think the term "tar" maybe be too broad. Do we mean "petroleum tar"? Do we have other terminologies from other protocols to use as a reference? Also, the inclusion of the last 2 suggested categories might be quite confusing. Maybe labels such as "undefined plastic" and "undefined non-plastic" would be more useful.

@gwemon We agree with all your suggestions:

- natural rubber
- natural fibres
- glass
- metal
- oil tar or petroleum tar as you wish (we have found the following article regarding tar (https://link.springer.com/article/10.1007/s11270-015-2298-5)
- undefined plastic
- undefined non-plastic

For us, it is fine to go ahead with this.
Thanks
