### ISSUE TITLE
Broaden the H05 vocabulary to include the information related to the microlitter material and the polymer type. Change the name of the vocabulary to EMODnet micro-litter materials and/or polymer types

### ISSUE THREAD

**Issue by mmolinajack** [nvs-vocabs/EMODnetChemVocabs#20]
Microlitter particles are not always plastic made. It would be desirable to include in H05 the necessary terms to describe the artificial non plastic material or the plastic material (in absence of the specific polymer type characterization) and change the name of the vocabulary to EMODnet micro-litter materials and/or polymer types.

**Comment by gwemon** [comment]
the following changes have been queued for publication on the NVS: 
new title='EMODnet micro-litter material or polymer type',
new short_name='Microlitter_material+polymer',
new definition='Controlled vocabulary defining the terms that may be used for micro-litter particle characterisation according to the type of non-plastic material or the type of plastic polymer in the EMODnet Chemistry data reporting system.'

**Comment by mmolinajack** [comment]
Thanks @gwemon!
