### ISSUE TITLE
Additional terms Microlitter polymer types (H05)

### ISSUE THREAD

**Issue by mmolinajack** [nvs-vocabs/EMODnetChemVocabs#23]
Based on the most recent literature regarding the microlitter research we propose to include 2 additional polymer types in the vocabulary:

- Acrylonitrile butadiene styrene (ABS)
- Styrene-butadiene rubber (SBR): synthetic rubber formed from a copolymer of styrene and butadiene

**Comment by gwemon** [comment]
@mmolinajack FYI
