### ISSUE TITLE
Microlitter polymer types (H05):Polyester and PET; Polychlorinated polymers and PVC

### ISSUE THREAD

**Issue by mmolinajack** [nvs-vocabs/EMODnetChemVocabs#24]
We have 2 terms in the vocabulary that might be the same one, i.e. polyethylene terephthalate, PET (H0500011) that is a type of polyester (H0500005).We propose to deprecate  PET (H0500011) and have a generic one  (polyester (H0500005)) with the definition: All types of polyesters including PVC.
In the same way, we have the term PVC (H0500009) but we don’t have a generic term to describe other polychlorinated polymers. We propose to have a unique generic term to include All Polychlorinated polymers including PVC.

**Comment by gwemon** [comment]
@mmolinajack  Changes are live on the NVS; please check and let me know if there are any issues.

**Comment by mmolinajack** [comment]
Thanks @gwemon, everything seems correct!
