### ISSUE TITLE
Microlitter polymer types (H05). Improvement of definitions

### ISSUE THREAD

**Issue by mmolinajack** [nvs-vocabs/EMODnetChemVocabs#25]
The H05 vocabulary does not contain definitions for the existing terms. We propose a definition for some of them based on the most recent literature:
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-7f4cb76b-7fff-aa3c-44a1-045f1636e9c5"><div dir="ltr" style="margin-left:0pt;" align="left">

Concept URI | prefLabel | altLabel | Proposed Definition

[H0500001](http://vocab.nerc.ac.uk/collection/H05/current/H0500001/) | polyethylene | PE | High-Density polyethylene, Low-Density polyethylene, and copolymers with a major polyethylene fraction
[H0500002](http://vocab.nerc.ac.uk/collection/H05/current/H0500002/) | polypropylene | PP | Polypropylene (PP) copolymers with a major PP fraction
[H0500003](http://vocab.nerc.ac.uk/collection/H05/current/H0500003/) | polystyrene | PS | Polystyrene (PS) copolymers with a major PS fraction
[H0500004](http://vocab.nerc.ac.uk/collection/H05/current/H0500004/) | polyamide (nylon) | PA | All types of polyamide (PA) like the various nylons
[H0500005](http://vocab.nerc.ac.uk/collection/H05/current/H0500005/) | polyester | PES | All types of polyesters including PET
[H0500006](http://vocab.nerc.ac.uk/collection/H05/current/H0500006/) | acrylic | PAN | Polyacrylonitrile
[H0500007](http://vocab.nerc.ac.uk/collection/H05/current/H0500007/) | polyoxymethylene | POM |  
[H0500008](http://vocab.nerc.ac.uk/collection/H05/current/H0500008/) | polyvinyl alcohol | PVAL |  
[H0500009](http://vocab.nerc.ac.uk/collection/H05/current/H0500009/) | polyvinylchloride | PVC | not available #24
[H0500010](http://vocab.nerc.ac.uk/collection/H05/current/H0500010/) | polymethylacrylate | PMA | All types of Polymethyl(ester)Acrylate
[H0500011](http://vocab.nerc.ac.uk/collection/H05/current/H0500011/) | polyethylene terephthalate | PET | not available #24
[H0500012](http://vocab.nerc.ac.uk/collection/H05/current/H0500012/) | alkyd | AK |  
[H0500013](http://vocab.nerc.ac.uk/collection/H05/current/H0500013/) | polyurethane | PU | All types of polyurethane

**Comment by gwemon** [comment]
@mmolinajack  Changes have been published on the NVS. Please check and let me know if there are any issues.
