### ISSUE TITLE
New term in H01 vocabulary (EMODnet micro-litter types)

### ISSUE THREAD

**Issue by mmolinajack** [nvs-vocabs/EMODnetChemVocabs#26]
The data reported in the Mediterranean follows UNEP  MAP protocol that contains the term granules to describe the morphology of the particles. We would need to include the type "granule" in micro-litter vocabulary:

Preferred label: microplastic granule

Alt label: granule

Definition: spherical shape, with a regular round shape bead.

@gwemon please, let us know if you need any additional information.

**Comment by gwemon** [comment]
@mmolinajack how does "granule" differs from "pellet" (http://vocab.nerc.ac.uk/collection/H01/current/H0100003/)? Are "pellets" never round? I haven't looked too deeply into it but from first read I thought these two terms would almost be synonyms. I might be wrong!

**Comment by gwemon** [comment]
To also be looked at bearing in mind other proposed changes to H01: https://github.com/nvs-vocabs/EMODnetChemVocabs/issues/19

**Comment by mmolinajack** [comment]
Hi @gwemon,
unfortunately we cannot find a consistent definition of granules and pellets (and the differences between them) on the literature. We have decided that it is better to ask the TGML group for advice. We will include you on the discussion.

**Comment by mmolinajack** [comment]
Hi @gwemon,
following the discussions with the TGML group, we would like to agree with you on a possible definition for granules and once we arrive to an agreement we would inform TGML that if they do not have anything against we will publish the new term. 
We propose the following definition for granule: Micro-litter particles with spherical shape, regular and smooth.
The definition of pellets could also be adjusted: Regularly-shaped, rough micro-litter particles.In the protocol that Marco Matiddi suggested: https://accedacris.ulpgc.es/bitstream/10553/114417/1/Report_Monitoring-microlitter-ingestion-in-marine-fish.pdf you can find some pictures with both types (p.20).
Thanks!

**Comment by gwemon** [comment]
Thank you @mmolinajack. Nice reference document. Why not adopt the same definitions as in Matiddi et al? I think it would help the users.
i.e.
Granule: Micro-litter particles with smooth spherical shape. In comparison with pellets, they have a regular round shape and usually a smaller size, around 1 mm in diameter. They appear in natural colours (white, beige, brown).

Pellet: Micro-litter particles from industrial origin only. They are usually flat on one side and can be of various colours, irregular, round shapes, and normally bigger in size, around 5 mm in diameter.

We could cite the source (ideally using DOI but could also cite as "adapted from Matiddi et al 2021")

**Comment by mmolinajack** [comment]
Hi @gwemon ,
We agree that it is a good reference document. 
After all the discussions we had with the expert group, we would prefer to avoid the inclusion of the information regarding size and color, to avoid having information from one vocabulary inside a different one. From the image in p.20, we think that an important difference is the fact that granules have a smooth surface while pellets have a rough one. If you want to adapt the definition from Matiddi et al we would propose:

- Granule: Micro-litter particles with smooth spherical shape. In comparison with pellets, they have a regular round shape and usually a smaller size.

- Pellet: Micro-litter particles from industrial origin only. They are usually flat on one side, rough surface and irregular, round shapes. Normally bigger in size.

What do you think?

Thanks

**Comment by gwemon** [comment]
@mmolinajack yes that's fine. I think we need to add "In comparison with granules," to the pellets' definition so that we have:
"Pellet: Micro-litter particles from industrial origin only. In comparison with granules, pellets are usually flat on one side, rough surface and irregular, round shapes. Normally bigger in size."

**Comment by mmolinajack** [comment]
Hi @gwemon,
we agree with your proposal.
The expert group discussions have been moved to the TGML wiki. We will post our proposal regarding the definition and if by the end of the week we don't receive a negative comment we will let you know to create/update the terms.

**Comment by mmolinajack** [comment]
Dear Gwen,
We were hoping to receive help and a common definition for the term "granule" from the TGML microlitter group. After our last exchange we thought we had a quite good proposal (based on Marco Matiddi protocol) but we received a comment from Assa Andersson in the TGML wiki (see below), we are just stuck without a clear position of how to proceed with this term. On the other hand, we are receiving pressures to finish the formatting of the italian microlitter data that requires the term. 
What would you advice to do? To surrender to the apparent impossibility to homogenize the present  heterogeneity of the different protocols and create a definition for every single protocol? We already know that this will lead to incomparable information but from the other side this is blocking all the data gathering process...there is no guarantee that discussing this at TGML we will have the desired solution....
Thanks and best regards,
Eugenia, Matteo and Elena

-------
Dear all,

I will start off by saying that I have not been taking part in the discussions within the microlitter restricted group, so the purpose of defining pellets and granules is not clear to me. Could it be problematic to try to define a vocabulary that is used with so many synonyms on similar objects?

Primary microplastic, ie what comes out of a factory as small particles, can come in many different sizes and shapes. A common shape is a wafer shape with a slight collapse in the middle, much like a bagel with no holes in the middle. These are often called pellets or in the United States more often nurdles. However, some often come out as spaghetti that is cut off so they have a different shape. Usually 3-4mm.

Then there are smaller particles that have an irregular shape, these are often called granules, or sometimes fluff or powder. Can be from a few tens to a few hundred μm.

Then we have spherical or near spherical, which are often expanded, ie contain gas or air. Microspheres are a common name.

I think Frank Jensen made a valuable point in his comments regarding the possible underestimation of lost pellets if we would be using the suggested definition of pellets. Could there be other problems? Perhaps you already have had a discussion of the pros and cons of making these definitions within the restricted microlitter group?  

All the best,

Åsa

--------

**Comment by gwemon** [comment]
Dear @mmolinajack and All, if people use both granules and pellets in a given dataset then there must be criteria to distinguish them unless the terms are used interchangeably? We could accommodate the terms "pellets " and "granules" but we somehow need to explain what makes the 2 concepts different from each other. The definition we had was not very strict but just saying that they are "usually". So I think that this would accommodate for the variation Asa is talking about. I am not sure I understand Asa's question though: "Could it be problematic to try to define a vocabulary that is used with so many synonyms on similar objects?". Does he/she imply that "pellet" and "granules" are synonyms and can be used interchangeably? but then the remainder of his/her text seems to show that there are important differences. Alternatively if the boundaries between the 2 terms are so blurred, then we might be better creating a concept that regroups the 2. However this would not work if the 2 categories are sometimes used in the same dataset.

**Comment by mmolinajack** [comment]
Hi @gwemon, 
Thanks for your prompt reply. We agree with your proposal, let's go for the definitions we drafted. In case regrouping is needed, users can do it on their convenience.

**Comment by mmolinajack** [comment]
Hi @gwemon, 
considering that there are discrepancies regarding the definition of the granules, we would like to propose the inclusion of the protocol as you had proposed in the beginning:

> We could cite the source (ideally using DOI but could also cite as "adapted from Matiddi et al 2021")

The document does not have a DOI but we could complete the definition like:
H0100009 granules Micro-litter particles with smooth spherical shape. In comparison with pellets, they have a rounder shape and are smaller in size (adapted from Matiddi et al, 2021).
Do you agree?

**Comment by gwemon** [comment]
Term and corrections are live: http://vocab.nerc.ac.uk/collection/H01/current/H0100009/
