### ISSUE TITLE
H05 vocabulary. Additional materials for micro-litter description

### ISSUE THREAD

**Issue by mmolinajack** [nvs-vocabs/EMODnetChemVocabs#29]
Hi @gwemon,
I copy here the request we had made some time ago regarding the additonal material clasess. It was embed on an issue regarding H01. This will solve Kati Lind request. Thanks

> @mmolinajack @mattevi78 Regarding required changes to H05 to cater for non-plastic material, you suggested: "We propose to create generic and specific terms, to cover all the possibilities: rubber, natural fibers, glass, metal, tar, plastic, non-plastic, non-plastic man-made" We already have synthetic rubber in H05 so just having a term "rubber" would be confusing. How about "natural rubber"? then "natural fibres", "glass", "metal". I think the term "tar" maybe be too broad. Do we mean "petroleum tar"? Do we have other terminologies from other protocols to use as a reference? Also, the inclusion of the last 2 suggested categories might be quite confusing. Maybe labels such as "undefined plastic" and "undefined non-plastic" would be more useful.

@gwemon We agree with all your suggestions:

- natural rubber
- natural fibres
- glass
- metal
- oil tar or petroleum tar as you wish (we have found the following article regarding tar (https://link.springer.com/article/10.1007/s11270-015-2298-5)
- undefined plastic
- undefined non-plastic

For us, it is fine to go ahead with this.
Thanks

_Originally posted by @mmolinajack in https://github.com/nvs-vocabs/EMODnetChemVocabs/issues/19#issuecomment-1177549585_

**Comment by mmolinajack** [comment]
Hi @gwemon,
did you have time to have a look at this issue?
Thanks

**Comment by gwemon** [comment]
Thank you for the reference paper about tar @mmolinajack . Very interesting. I am proposing to replace oil tar or petroleum tar with "Tar residue". do you agree?
Also I am proposing the following definitions:
natural rubber - "The litter material consists of rubber from natural sources of polymers of the organic compound isoprene, with minor impurities of other organic compound; also called India rubber, latex, Amazonian rubber, caucho, or caoutchouc. Adapted from Wikipedia entry retrieved 18 October 2022."
natural fibres/fibers - The litter material consists of natural fibres which are threads or filaments produced by natural processes.
glass - The litter material consists of hard, transparent material made from the melting of sand (silica), soda ash (sodium carbonate) and limestone (calcium carbonate). 
metal - The litter material is metallic.
tar residue - The litter material consists of weathered oil conglomerations originating from natural or anthropogenic oil released in the environment.
undefined plastic - The litter material was classified as plastic but its precise nature was not recorded. 
undefined non-plastic  - The litter material was classified as non-plastic but its precise nature was not recorded.

**Comment by mmolinajack** [comment]
> Thank you for the reference paper about tar @mmolinajack . Very interesting. I am proposing to replace oil tar or petroleum tar with "Tar residue". do you agree? 
Yes.

> Also I am proposing the following definitions: natural rubber - "The litter material consists of rubber from natural sources of polymers of the organic compound isoprene, with minor impurities of other organic compound; also called India rubber, latex, Amazonian rubber, caucho, or caoutchouc. Adapted from Wikipedia entry retrieved 18 October 2022." 
Ok

> natural fibres/fibers - The litter material consists of natural fibres which are threads or filaments produced by natural processes. 
Ok

> glass - The litter material consists of hard, transparent material made from the melting of sand (silica), soda ash (sodium carbonate) and limestone (calcium carbonate). 
Ok

> metal - The litter material is metallic. 
We would propose to adapt the the definition of metal from the Wikipedia: The litter material is metallic, i.e. a matter that, when freshly prepared, polished, or fractured, shows a lustrous appearance, and conducts electricity and heat relatively well. Adapted from Wikipedia entry retrieved 19 October 2022. What do you think?

> tar residue - The litter material consists of weathered oil conglomerations originating from natural or anthropogenic oil released in the environment. 
Ok
> undefined plastic - The litter material was classified as plastic but its precise nature was not recorded. 
Ok
> undefined non-plastic - The litter material was classified as non-plastic but its precise nature was not recorded.
Ok
Thanks @gwemon

**Comment by gwemon** [comment]
Terms are live on the NVS as follows:
<html>
<body>


Identifier | Preferred label | Alternative label | Definition | Date
-- | -- | -- | -- | --
[H0500026](https://vocab.nerc.ac.uk/collection/H05/current/H0500026) | undefined non-plastic |   | The litter material was classified as non-plastic but its precise nature was not recorded. | 2022-10-25
[H0500025](https://vocab.nerc.ac.uk/collection/H05/current/H0500025) | undefined plastic |   | The litter material was classified as plastic but its precise nature was not recorded. | 2022-10-25
[H0500024](https://vocab.nerc.ac.uk/collection/H05/current/H0500024)  | metal |   | The litter material is metallic, i.e. a matter that, when freshly prepared, polished, or fractured, shows a lustrous appearance, and conducts electricity and heat relatively well. Adapted from Wikipedia entry retrieved 19 October 2022. | 2022-10-25
[H0500023](https://vocab.nerc.ac.uk/collection/H05/current/H0500023)  | glass |   | The litter material consists of hard, transparent material made from the melting of sand (silica), soda ash (sodium carbonate) and limestone (calcium carbonate). | 2022-10-25
[H0500022](https://vocab.nerc.ac.uk/collection/H05/current/H0500022)  | natural fibres |   | The litter material consists of natural fibres which are threads or filaments produced by natural processes. | 2022-10-25
[H0500021](https://vocab.nerc.ac.uk/collection/H05/current/H0500021)  | natural rubber |   | The litter material consists of rubber from natural sources of polymers of the organic compound isoprene, with minor impurities of other organic compound; also called India rubber, latex, Amazonian rubber, caucho, or caoutchouc. Adapted from Wikipedia entry retrieved 18 October 2022. | 2022-10-25
[H0500020](https://vocab.nerc.ac.uk/collection/H05/current/H0500020)  | tar residue |   | The litter material consists of weathered oil conglomerations originating from natural or anthropogenic oil released in the environment. | 2022-10-25

**Comment by mmolinajack** [comment]
Thanks @gwemon
