### ISSUE TITLE
Deprecate P35 terms

### ISSUE THREAD

**Issue by mmolinajack** [nvs-vocabs/EMODnetChemVocabs#30]
Hi @gwemon 
as discussed, we include here the list of terms in P35 vocabulary that are not used anymore. The terms can be deprecated.
[P35_vocabulary_ML.xlsx](https://github.com/nvs-vocabs/EMODnetChemVocabs/files/10029525/P35_vocabulary_ML.xlsx)

**Comment by gwemon** [comment]
Terms related to contaminant concentrations in biota, sediment and water bodies in the EMODnet chemistry workflow, are no longer aggregated using the P35 aggregated terms. Decision was taken at EMODnet chemistry meeting of 15-nov-2022 to deprecate them in order to declutter P35 and avoid confusion.

**Comment by gwemon** [comment]
157 concept id deprecated in P35. Changes will be live on the NVS within 24h.
