### ISSUE TITLE
P36 "Heavy metals" BODCNVS-1721

### ISSUE THREAD

**Issue by MeganAnneFrench** [nvs-vocabs/EMODnetChemVocabs#35]
Hi,
As discussed in the meeting between OGS, Gwen (BODC), and Hans (ICES) on 20 February 2023, the name of the P36 "Heavy metals" should be changed to "Metals and metalloids" (as used by ICES) because many metals and metalloids are not heavy metals. The suggested definition change is: "Concentrations of metals, metalloids, and selenium (a reactive non-metal), some of which are of environmental concern."

**Comment by gwemon** [comment]
Done. The changes will be live tomorrow.

**Comment by gwemon** [comment]
@MeganAnneFrench  while doing these updates I realised that there are still a lot of mappings between P36 and P35. Am I correct to understand that these mappings are now redundant and can be removed? It would help declutter the section showing the relationships between P36 and P02 as in here for example:  http://vocab.nerc.ac.uk/collection/P36/current/HVYMTL/

**Comment by mlipizer** [comment]
For EMODnet Chemistry P36 maps the "tender requested macro-categories" and is used in the CDI filtering; P35 is needed for ODV to aggregate "similar" P01 and to practically aggreagate/merge P01, we use it only for some macro-categories (eutrophication-related, T & S,...). So, no P35 are needed for contaminants (for EMD Chem). I do not think mapping between P34 and P36 is requested. Does this answere?

**Comment by gwemon** [comment]
> For EMODnet Chemistry P36 maps the "tender requested macro-categories" and is used in the CDI filtering; P35 is needed for ODV to aggregate "similar" P01 and to practically aggreagate/merge P01, we use it only for some macro-categories (eutrophication-related, T & S,...). So, no P35 are needed for contaminants (for EMD Chem). I do not think mapping between P34 and P36 is requested. Does this answere?

So @mlipizer am I correct to think that we can remove all mappings between P35 and P36?
