### ISSUE TITLE
P35-P01 revisions BODCNVS-1748

### ISSUE THREAD

**Issue by mlipizer** [nvs-vocabs/EMODnetChemVocabs#38]
Dear colleagues,
we need following corrections on P01-P35 connections:
P01: OPHSVLPT Concentration of organic phosphorus {organic_P CAS 7723-14-0} {POP} per unit volume of the water body [particulate >unknown phase]
**must be eliminated from** P35 EPC00153 Water body organic phosphorus
and moved to a **NEW P35**: Water body particulate organic phosphorus {POP}

Then following P01 (currently NULL P35) should go to the listed P35:
CHLTVOLU **to** EPC00105
NTRZKGD1 **to** EPC00005
DOXYSC02 **to** EPC00002
NTCOKGD1 **and** NTOTCOD1 **to** EPC00160
NTOTKJM1 **to** EPC00134
TPHSWCD3 **to** 	EPC00186

Thanks for your collaboration, Marina

**Comment by gwemon** [comment]
@mlipizer so are you saying that http://vocab.nerc.ac.uk/collection/P35/current/EPC00153/ should only be dissolved organic phosphorus?
Also, we already have: http://vocab.nerc.ac.uk/collection/P35/current/EPC00201/ for particulate phosphorus. Will that not be confusing if we now also create a code for particulate organic phosphorus? what is the use case for the separation of phosphorus into these three P35 aggregations?

**Comment by gwemon** [comment]
@mlipizer CHLTVOLU is a very generic code for "chlorophyll" - any chlorophylls, coming from any kind of measurements, possibly even from uncalibrated fluorometer outputs. Are you asking for its inclusion because you know that it is being used instead of more specific codes? Do we know how often this code is used in the SeaDataNet network and with what kind of L22 instrumentation?

**Comment by gwemon** [comment]
@mlipizer please let me know about the 2 open questions:
CHLTVOLU to EPC00105 --> see my comment above (this is not "chlorophyll-a" but "chlorophyll") --> still okay to proceed?
NTRZKGD1 to EPC00005 --> done
DOXYSC02 to EPC00002 --> if we do this then whenever a DOXYSC02 value is present (probably mainly from datasets coming from BODC CTD processed casts) then it will duplicate a DOXYSC01 value so an average or a selection will need to be made if duplicate data points are not accepted; is it still okay to proceed?
NTCOKGD1 and NTOTCOD1 to EPC00160 --> done
NTOTKJM1 to EPC00134 --> done
TPHSWCD3 to EPC00186 --> done

**Comment by mlipizer** [comment]
> @mlipizer so are you saying that http://vocab.nerc.ac.uk/collection/P35/current/EPC00153/ should only be dissolved organic phosphorus? 
_The issue is that dissolved or total (filtered and unfiltered phase) **cannot be aggregated** with particulate (> some filtered phase). The particulate phase is (usually) much lower than dissolved. This means that aggregating filtered (< some filter) and unfiltered phase is acceptable, while particulate phase should be kept separated._

Also, we already have: http://vocab.nerc.ac.uk/collection/P35/current/EPC00201/ for particulate phosphorus. Will that not be confusing if we now also create a code for particulate organic phosphorus? what is the use case for the separation of phosphorus into these three P35 aggregations?
_Your comment is correct. Besides, the P02 is "Particulate total and organic phosphorus concentrations in the water column" which combines total (EPC00201) and organic. SO: no need to create a new a code for particulate organic phosphorus.
Sorry for this._

**Comment by mlipizer** [comment]
> CHLTVOLU

I see your point. We will evaluate these issues. PLEASE DO NOT PROCEED (thank you)

**Comment by mlipizer** [comment]
> DOXYSC02 to EPC00002 --> if we do this then whenever a DOXYSC02 value is present (probably mainly from datasets coming from BODC CTD processed casts) then it will duplicate a DOXYSC01 value so an average or a selection will need to be made if duplicate data points are not accepted; is it still okay to proceed?

I do not understand clearly this. IS this code used for duplicated data acquired at the same time/place of "first sensors"?

**Comment by gwemon** [comment]
> > DOXYSC02 to EPC00002 --> if we do this then whenever a DOXYSC02 value is present (probably mainly from datasets coming from BODC CTD processed casts) then it will duplicate a DOXYSC01 value so an average or a selection will need to be made if duplicate data points are not accepted; is it still okay to proceed?
> 
> I do not understand clearly this. IS this code used for duplicated data acquired at the same time/place of "first sensors"?

@mlipizer it's for duplicated sensor on the same platform. i.e. a "secondary" sensor that is effectively a duplicate sensor in case of the the sensors fail. Was just flagging this in case it complicates your checks for duplicates. hey should be reading the same value unless there is an issue with one of the sensor.

**Comment by mlipizer** [comment]
Dear Gwen, we had an internal meeting with regional leaders and it was proposed to leave this P01 outside P35 for the moment. So: no action on this issue. Thank yoy
