### ISSUE TITLE
New P35 to be created (BODCNVS-1748)

### ISSUE THREAD

**Issue by mlipizer** [nvs-vocabs/EMODnetChemVocabs#39]
Dear colleagues,
we need following new P35 term: "Water body dissolved oxygen concentration-Not calibrated" or something similar to aggregated not calibrated sensor data of oxygen.
**Following P01 must be removed from: EPC00002 and added to the new P35**
List of P01 to be moved:
DOXYSU01
DOXYSU02
DOXYUZ01
DOXYUZ02

Thanks for your collaboration

**Comment by gwemon** [comment]
@mlipizer I will remove the uncalibrated codes from the mapping. However, before we create a P35 entry for uncalibrated sensor data we need to think carefully about the use case. What would be the purpose of creating a specific P35 code for uncalibrated sensor data? And if we do it for oxygen then would this not be something we would have to do for other sensor variables? Do we really want or need this?

**Comment by gwemon** [comment]
Mappings of 
[DOXYSU01](http://vocab.nerc.ac.uk/collection/P01/current/DOXYSU01/)
[DOXYSU02](http://vocab.nerc.ac.uk/collection/P01/current/DOXYSU02/)
[DOXYUZ01](http://vocab.nerc.ac.uk/collection/P01/current/DOXYUZ01/)
[DOXYUZ02](http://vocab.nerc.ac.uk/collection/P01/current/DOXYUZ02/) to [EPC00002](http://vocab.nerc.ac.uk/collection/P35/current/EPC00002/) removed.

**Comment by gwemon** [comment]
@mlipizer Please see my questions in previous comment regarding creation of new code. Maybe a quick zoom call will be needed to look at the options.

**Comment by mlipizer** [comment]
Dear Gwen, please let's keep the creation of the uncalibrated P35 pending. Your comments are correct. We need further discussion. Thank you

**Comment by gwemon** [comment]
Okay thanks @mlipizer I am closing this ticket. We can re-open it if/when a decision is made.
