### ISSUE TITLE
Opinion requested: P35 Water body chlorophyll-a: radiometer data? (BODCNVS-1748)

### ISSUE THREAD

**Issue by mlipizer** [nvs-vocabs/EMODnetChemVocabs#40]
Dear colleagues,
we are not sure whether following P01 are correctly in P35 Water body chlorophyll-a:

1. CPHLUA01 Concentration of chlorophyll-a {chl-a CAS 479-61-8} per unit volume of the water body [particulate >unknown phase] by radiometer and computation from the ratio of upwelled irradiance at 440 and 570 nm
2. CPHLUB01 Concentration of chlorophyll-a {chl-a CAS 479-61-8} per unit volume of the water body [particulate >unknown phase] by radiometer and computation from the ratio of upwelled irradiance at 490 and 570 nm

Are these satellite data? We are not sure if it is correct to aggregate these P01 with in situ (bottle) and fluorometer (CTD, sensosrs) data.
What is you opinion?

**Comment by gwemon** [comment]
@mlipizer these codes were created in 1999 and I believe that they were created to support data coming from a field deployment of a portable radiometer as part of a cross-calibration exercise of satellite measurements. They do not represent a lot of data points but to avoid confusion I agree that it would be best to remove them from the P35 mapping.

**Comment by gwemon** [comment]
Mappings removed and changes will be live after the overnight refresh.
