### ISSUE TITLE
Help needed with definition of the various Imposex indices RPSI, RPLI and VDSI

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/EMODnetChemVocabs#41]
I hope somebody will be able to help here. As far as I can understand from my internet search, there are 3 indices used for monitoring the impact of organotin on gastropods: Relative Penis Size Index, Relative Penis Length Index and the Vas Deference Sequence Index. Can anybody point me to a reliable source of definition for these 3 indices please? They are referred to a lot but I cannot find the original source of the definition and have no access to the often quoted paper by Gibb and Bryan 1994.

**Comment by MeganAnneFrench** [comment]
I don't know if it is useful, but there is some info about RPS in the attached, Gibbs and Bryan 1987
[Gibbs and Bryan 1987.pdf](https://github.com/nvs-vocabs/EMODnetChemVocabs/files/11834354/Gibbs.and.Bryan.1987.pdf)

**Comment by MeganAnneFrench** [comment]
Citation 11 within that paper for VDS is here:
[Gibbs et al. 1987.pdf](https://github.com/nvs-vocabs/EMODnetChemVocabs/files/11834431/Gibbs.et.al.1987.pdf)

**Comment by MeganAnneFrench** [comment]
Here is another of their papers on this topic:
[Gibbs et al. 1988.pdf](https://github.com/nvs-vocabs/EMODnetChemVocabs/files/11834454/Gibbs.et.al.1988.pdf)

**Comment by gwemon** [comment]
Thank you @MeganAnneFrench at least I have enough now to define the RPS index.

**Comment by gwemon** [comment]
I have found an ICES report in the OBPS repository: https://repository.oceanbestpractices.org/handle/11329/715 which I will use as my main source.
