### ISSUE TITLE
New S27 request: ISPRA/OGS PAH sum [BODCNVS-1995]

### ISSUE THREAD

**Issue by mlipizer** [nvs-vocabs/EMODnetChemVocabs#43]
I was confirmed that the originator requires a new S27 which should be something like:

ISPRA/OGS PAH sum 
SIMILAR TO: 
[CS003044](http://vocab.nerc.ac.uk/collection/S27/current/CS003044)	IMS PAH mixture I

Description: A mixture of 15 polycyclic aromatic hydrocarbons given priority by the EPA (naphthalene, acenaphthene, fluorene, phenanthrene, anthracene, fluoranthene, pyrene, benzo[a]anthracene, chrysene, benzo[b]fluoranthene, benzo[k]fluoranthene, benzo[a]pyrene, benzo[g,h,i]perylene, indeno[1,2,3-c,d]pyrene, dibenz[a,h]anthracene), whose concentrations are summed to produce an overall 'PAH concentration' by ISPRA (Institute for Environmental Protection and Research) and OGS (National Institute of Oceanography and Applied Geophysics), Italy

**Comment by mlipizer** [comment]
We are re-considering the term proposed: ISPRA/OGS PAH sum.We think it should not be linked to the institute but made more general.

**Comment by gwemon** [comment]
Hello @Osanna123 do you have this mixture in ICES?

**Comment by Osanna123** [comment]
We have a historical code SPAH, described as 'sum of PAHs (total)', without any additional details.
We have also codes for specific mixtures, like SPAH4 or SPAH9. 
I guess, in the given case we'd have created SPAH15 or asked to use the more generic SPAH in combination with method references.

**Comment by gwemon** [comment]
I think I would prefer to be more specific for the S27 entry. This is to cover cases when we may in the future receive combinations of 15 PAHs that do not match this combination of 15. Since the list of 15 is the same as the EPA 16 priority PAHs but without the acenaphthylene then, if it does not have any other known recognised name in the field, I'd prefer to go for a preferred label of the form 'EPA 16 priority polycyclic aromatic hydrocarbons minus acenaphthylene" with alternative label "EPA 16-1" or "EPA 16-acenaphthylene) i.e. similar to http://vocab.nerc.ac.uk/collection/S27/current/CS002800/ but without the excluded PAH.
We will also add mappings to the individual PAH as children record to this record (and to the other PAH mixtures too) to ensure that the constituents can easily be found easily.

**Comment by mlipizer** [comment]
I agree with this proposal Gwen. Thank you for looking into this

**Comment by roswri** [comment]
New term created and published:
[EPA 16 priority polycyclic aromatic hydrocarbons minus acenaphthylene](https://vocab.nerc.ac.uk/collection/S27/current/CS004484/)

**Comment by gwemon** [comment]
I re-opened this ticket because this request was really about the need for the new S27 but also the associated P01 code (in email trail). We will close once the P01 code is created.

**Comment by mlipizer** [comment]
dear colleagues, these are the pending P01 (with the newly created S27):

p01_label | p06 | p02
Concentration of EPA 16 priority polycyclic aromatic   hydrocarbons minus acenaphthylene per unit dry weight of biota {Chamelea   gallina (ITIS: 205649: WoRMS 141907) [Subcomponent: flesh]} | NGPG | BCAH
Concentration of EPA 16 priority polycyclic aromatic   hydrocarbons minus acenaphthylene per unit wet weight of biota {Ruditapes   philippinarum (WoRMS 231750) [Subcomponent: flesh]} | NGPG | BCAH
Concentration of EPA 16 priority polycyclic aromatic   hydrocarbons minus acenaphthylene per unit dry weight of biota {Solea solea   (ITIS: 173002: WoRMS 127160) [Subcomponent: muscle tissue]} | NGPG | BCAH
Concentration of EPA 16 priority polycyclic aromatic   hydrocarbons minus acenaphthylene per unit dry weight of biota {Squalus   acanthias (ITIS: 160617: WoRMS 105923) [Subcomponent: muscle tissue]} | NGPG | BCAH


When is it feasible for you? thanks

**Comment by danibodc** [comment]
Hi @mlipizer these have been completed - see https://github.com/nvs-vocabs/P01/issues/237#issuecomment-1906340756

**Comment by mlipizer** [comment]
thank you!
kind regards
Marina

___________________________________________________________

Marina Lipizer

Sezione di Oceanografia

Istituto Nazionale di Oceanografia e di Geofisica Sperimentale - OGS

Borgo Grotta Gigante, 42/c

34010 Sgonico (TS) - Italia

https://www.ogs.it/

e-mail: ***@***.*** ***@***.***>

Tel.: +39 040 2140310

Skype: marina.lipizer

http://www.ogs.trieste.it/it/users/marina-lipizer

http://orcid.org/0000-0001-5707-6338


Il giorno lun 12 feb 2024 alle ore 16:04 Dani Wright <
***@***.***> ha scritto:
