### ISSUE TITLE
New P01 for pH data [BODCNVS-2030]

### ISSUE THREAD

**Issue by mlipizer** [nvs-vocabs/EMODnetChemVocabs#44]
Dear colleagues,
we have been asked following P01:

1. pH (total scale) (pHT) of the water body by ion sensitive field-effect transistors (ISFET) sensor with Internal counter electrode and manufacturer's calibration applied
2. pH (total scale), (pHT) of the water body by ion sensitive field-effect transistors (ISFET) sensor with external counter electrode and manufacturer's calibration applied
3. pH (NBS scale) {pH[T]} of the water body by potentiometric glass electrode

We kindly ask if you could give this request a priority as these are operational data which need to be available as soon as possible. Thank you and sorry for being pressing.

In addition, from a long internal discussion, it was suggested that some codes (listed below) need probably revision as they seem not coherent with current techniques.

PHXXSP03: pH (total scale) {pH[T]} of the water body by spectrophotometry (internal electrode) and manufacturer's calibration applied
PHX XSP04: pH (total scale) {pH[T]}  of the water body by spectrophotometry (external electrode) and manufacturer's calibration applied
PHXXSP05: pH (total scale{pH[T]}) of the water body by spectrophotometry (external electrode) and manufacturer's calibration and correction against independent temperature and salinity measurements
PHXXSP06: pH (total scale) {pH[T]} of the water body by spectrophotometry (internal electrode) and manufacturer's calibration and correction against independent temperature and salinity measurements
PHXXSP07: pH (total scale) {pH[T]} of the water body by spectrophotometry (external electrode) and manufacturer's calibration and laboratory calibration against TRIS-buffer applied

**Comment by mlipizer** [comment]
sorry, code 3 as follows:
pH (NBS scale) of the water body by potentiometric glass electrode

to remove: {pH[T]}

**Comment by jakjonbodc** [comment]
Dear colleagues,

I would like to provide you with some additional information that our chemist has given us:
Three types of pH sensors are installed on the OGS buoys: potentiometric glass electrodes (SeaBird SBE18), ISFET potentiometric sensors (Sea-Brid SeaFET) and spectrophotometric sensors (Sunburst SAMIpH).

The first two parameters requested by Marina are proposed as an alternative to the definitions listed below, which in the opinion of our chemist are not appropriate (incorrect):
PHXXSP03: pH (total scale) {pH[T]} of the water body by spectrophotometry (internal electrode) and manufacturer's calibration applied
PHX XSP04: pH (total scale) {pH[T]}  of the water body by spectrophotometry (external electrode) and manufacturer's calibration applied
PHXXSP05: pH (total scale{pH[T]}) of the water body by spectrophotometry (external electrode) and manufacturer's calibration and correction against independent temperature and salinity measurements
PHXXSP06: pH (total scale) {pH[T]} of the water body by spectrophotometry (internal electrode) and manufacturer's calibration and correction against independent temperature and salinity measurements
PHXXSP07: pH (total scale) {pH[T]} of the water body by spectrophotometry (external electrode) and manufacturer's calibration and laboratory calibration against TRIS-buffer applied
The reason why these definitions are not applicable is that no spectrophotometric measurement is performed by the Seafet sensor, on which only ISFET sensors and electrochemical reference electrodes are installed.

The third parameter requested by Marina is proposed as an alternative to PHNBWCAL: pH (NBS scale) of the water body by computation, which is not appropriate for us.
In fact, the definition states: “Carbonate system parameter calculated from two of pCO2, DIC, TA and pH that have been directly measured in a sample collected from a water body”, while in our case the pH is not calculated from two variables of the carbonate system, but measured directly with the glass electrode.

I hope this can help to improve the coherence of the pH vocabulary.
With kind regards,
Alessandra

**Comment by jakjonbodc** [comment]
Created two new P01 terms in response to the first two of the three requested. Analytical method requires further clarification and has been queried by Sam.

PHXXFE02 - pH (total scale) {pH[T]} of the water body by ion sensitive field-effect transistor (ISFET) sensor (internal counter electrode) and manufacturer's calibration applied
https://vocab.nerc.ac.uk/collection/P01/current/PHXXFE02/

PHXXFE03 - pH (total scale) {pH[T]} of the water body by ion sensitive field-effect transistor (ISFET) sensor (external counter electrode) and manufacturer's calibration applied
https://vocab.nerc.ac.uk/collection/P01/current/PHXXFE03/

**Comment by mlipizer** [comment]
Please notice that the definition of:
h**ttps://vocab.nerc.ac.uk/collection/P01/current/PHNBISGE/**
is NOT CORRECT! It is the same as: https://vocab.nerc.ac.uk/collection/P01/current/PHNBWCAL/
and it should be: The concentration of hydrogen ions directly measured by the glass electrode

**Comment by jakjonbodc** [comment]
Thankyou for your feedback, please find:
PHNBISGE - pH (NBS scale) {pH[NBS]} of the water body by in-situ glass electrode
https://vocab.nerc.ac.uk/collection/P01/current/PHNBISGE/

The description has been amended in our system and will be updated online by tomorrow.
