### ISSUE TITLE
A question about 2,4'-dichlorodiphenyldichloroethane {o,p'-DDD mitotane CAS 53-19-0} and 2,4'-dichlorodiphenyldichloroethylene {o,p'-DDE CAS 3424-82-6}

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/EMODnetChemVocabs#45]
Dear All, we found an inconsistency in 2 of our P01 codes and I am trying to determine whether the error is in the Preferred Label or the Alternative Label and definition (https://github.com/nvs-vocabs/P01/issues/25). Would any of you (maybe @Osanna123 or @MeganAnneFrench) be able to help? Do you have data related to those 2 contaminants measured in water bodies in your systems (2,4'-dichlorodiphenyldichloroethane {o,p'-DDD mitotane CAS 53-19-0} and 2,4'-dichlorodiphenyldichloroethylene {o,p'-DDE CAS 3424-82-6})? If so are they exclusively measured on unfiltered water or filtered water? or could both occur?

**Comment by MeganAnneFrench** [comment]
Dear Gwen,
In the 2023 contaminants collection (all sea basins), we have CAS 53-19-0 as P01 TDEOPBF1 (definition: Concentration of 2,4'-dichlorodiphenyldichloroethane {o,p'-DDD mitotane CAS 53-19-0} per unit volume of the water body [dissolved plus reactive particulate phase]; harmonised local name: *Diss_oDDD_Filt {TDEOPBF1} [ug/l]), and CAS 3424-82-6 as P01 DDEOPBF1 (definition: Concentration of 2,4'-dichlorodiphenyldichloroethylene {o,p'-DDE CAS 3424-82-6} per unit volume of the water body [dissolved plus reactive particulate phase]; harmonised local name: *Diss_oDDE_filt {DDEOPBF1} [ug/l]). DDEOPBF1 data are only in the Atlantic, while TDEOPBF1 are mostly in the Atlantic but a small amount of data are also in the Mediterranean.
Megan

**Comment by Osanna123** [comment]
Dear Gwen,
All our water samples reported with these two contaminants were unfiltered.
Best regards,
Anna

**Comment by gwemon** [comment]
Thank you @Osanna123 . this makes me more confident in implementing the correction. I will close this ticket and we will correct the alternative label so that it is aligned with the preferred label that these contaminants are measured on unfiltered water.
